# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sq < Formula
  desc "sq: swiss-army knife for data"
  homepage "https://github.com/neilotoole/sq"
  version "0.22.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/neilotoole/sq/releases/download/v0.22.7/sq-0.22.7-macos-amd64.tar.gz"
      sha256 "77cda716bc53bd49ffa2a4878d72505f70aa95adaebed20e3293ce8cea3b284c"

      def install
        bin.install "sq"
        bash_completion.install "completions/sq.bash" => "sq"
        zsh_completion.install "completions/sq.zsh" => "_sq"
        fish_completion.install "completions/sq.fish"
        man1.install "manpages/sq.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/neilotoole/sq/releases/download/v0.22.7/sq-0.22.7-macos-arm64.tar.gz"
      sha256 "0e01afd4b16aca0ba48490caa60c4f3faf918559c205094d2b08f0567748ccdf"

      def install
        bin.install "sq"
        bash_completion.install "completions/sq.bash" => "sq"
        zsh_completion.install "completions/sq.zsh" => "_sq"
        fish_completion.install "completions/sq.fish"
        man1.install "manpages/sq.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neilotoole/sq/releases/download/v0.22.7/sq-0.22.7-linux-arm64.tar.gz"
      sha256 "48f6382a47734895af2471c19257ef92d3a13fac3ab2f36f78a266c2a1ce40a2"

      def install
        bin.install "sq"
        bash_completion.install "completions/sq.bash" => "sq"
        zsh_completion.install "completions/sq.zsh" => "_sq"
        fish_completion.install "completions/sq.fish"
        man1.install "manpages/sq.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/neilotoole/sq/releases/download/v0.22.7/sq-0.22.7-linux-amd64.tar.gz"
      sha256 "83bfb1236ca4cf02a2cf80abffe90fb12ab6dde927ad27842a4dfe27f62bacc0"

      def install
        bin.install "sq"
        bash_completion.install "completions/sq.bash" => "sq"
        zsh_completion.install "completions/sq.zsh" => "_sq"
        fish_completion.install "completions/sq.fish"
        man1.install "manpages/sq.1.gz"
      end
    end
  end

  test do
    system "#{bin}/sq --version"
  end
end
