# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sq < Formula
  desc "sq: swiss-army knife for data"
  homepage "https://github.com/neilotoole/sq"
  version "0.22.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/neilotoole/sq/releases/download/v0.22.5/sq-0.22.5-macos-amd64.tar.gz"
      sha256 "d9670d98b0099ed84da9e8dc753ce738ff2b2be459bb84d4dd838b8c2e40d40e"

      def install
        bin.install "sq"
        bash_completion.install "completions/sq.bash" => "sq"
        zsh_completion.install "completions/sq.zsh" => "_sq"
        fish_completion.install "completions/sq.fish"
        man1.install "manpages/sq.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/neilotoole/sq/releases/download/v0.22.5/sq-0.22.5-macos-arm64.tar.gz"
      sha256 "b7f52e7af1429fc6b67a4d33caa1de0520b2cca4ef1b8293dc4cadb88b93f45a"

      def install
        bin.install "sq"
        bash_completion.install "completions/sq.bash" => "sq"
        zsh_completion.install "completions/sq.zsh" => "_sq"
        fish_completion.install "completions/sq.fish"
        man1.install "manpages/sq.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neilotoole/sq/releases/download/v0.22.5/sq-0.22.5-linux-arm64.tar.gz"
      sha256 "129296e8d428c1aff2ccd53f930b4c771bd2871a13274dd5ea3f8fff1c043a0e"

      def install
        bin.install "sq"
        bash_completion.install "completions/sq.bash" => "sq"
        zsh_completion.install "completions/sq.zsh" => "_sq"
        fish_completion.install "completions/sq.fish"
        man1.install "manpages/sq.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/neilotoole/sq/releases/download/v0.22.5/sq-0.22.5-linux-amd64.tar.gz"
      sha256 "e3982c04ac1cce3646c9a9fd3f7da5f82a18664f93f0cb5b8a026f695803fc88"

      def install
        bin.install "sq"
        bash_completion.install "completions/sq.bash" => "sq"
        zsh_completion.install "completions/sq.zsh" => "_sq"
        fish_completion.install "completions/sq.fish"
        man1.install "manpages/sq.1.gz"
      end
    end
  end

  test do
    system "#{bin}/sq --version"
  end
end
