# This file was generated by GoReleaser. DO NOT EDIT.
class Sq < Formula
  desc "sq is sed for structured data"
  homepage "http://sq.io"
  version "0.5.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/neilotoole/sq-preview/releases/download/v0.5.4/sq-preview-0.5.4-macos.tar.gz"
    sha256 "87444364a2073d88c0b567d4d005bb588c107146951e531e7db64f7b0e66f521"
  elsif OS.linux?
  end

  def install
    bin.install "sq"
  end

  test do
    system "#{bin}/sq version"
  end
end
