# This file was generated by GoReleaser. DO NOT EDIT.
class Sq < Formula
  desc "sq is a swiss army knife for data"
  homepage "https://sq.io"
  version "0.14.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/neilotoole/sq/releases/download/v0.14.6/sq-0.14.6-macOS-amd64.tar.gz"
    sha256 "12a407cc79bb04f17782fda92ad33fb8d2f5103950c4fc4c494825fbc9ac1905"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/neilotoole/sq/releases/download/v0.14.6/sq-0.14.6-linux-amd64.tar.gz"
    sha256 "07bf61fee42b29fb0032d9b2ec2ba6662c6f6810cf9c61dae1167dd7111b17fa"
  end

  def install
    bin.install "sq"
  end

  def caveats; <<~EOS
    This is a preview release of sq. Use with caution.
  EOS
  end

  test do
    system "#{bin}/sq version"
  end
end
